# Generated by Django 2.1 on 2019-07-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abv', models.IntegerField()),
                ('ibu', models.IntegerField()),
                ('srm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('on_hand_qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Detail')),
            ],
        ),
    ]
