# Generated by Django 2.1 on 2019-07-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail',
            new_name='detail_id',
        ),
    ]
