# Generated by Django 2.1 on 2019-07-29 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20190713_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand_Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_score', models.IntegerField()),
                ('detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Detail')),
            ],
        ),
    ]
